# Configuration flags for site customization

#Setup
title: Cindy Liu                         # displayed in header
tagline: not all who wander are lost.    # displayed in header
description:                             # displayed in sidebar
avatar: /images/back-pic.png            # displayed in sidebar
url: http://liucindy.github.io           # used for Sitemap.xml and RSS feed
permalink: /:title/
paginate: 5

# Footer (includes an icon in the footer for each username entered)
footer-links:
  dribbble:
  email: cindyliu@princeton.edu
  facebook:
  flickr: 125645735@N04
  github: liucindy
  instagram:
  linkedin:
  pinterest:
  rss: # type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UC9pi-MItQ_mpSs-TDVByLDQ # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in profile username that comes after plus.google.com/

collections:
  photography:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# The release of Jekyll Now and Lanyon themes that I'm using
version_jekyll_now: 1.2.0
version_lanyon: 1.0.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as I'm using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate # Allow pagination

# Exclude these files from _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
